import { testIds } from '../../../shared/dataTestIds'

describe('Check Buying Preference for consumer flow with Empty Trade', () => {
  context('Buying Preference for consumer flow', () => {
    before(() => {
      cy.clearAllLocalStorage()
      cy.clearAllCookies()
      cy.visit(testIds.url_base)
      cy.getByData('producer_button').click()
      cy.getByData(testIds.auth_inputEmail).type(testIds.user_validEmail_producer_flow)
      cy.getByData(testIds.auth_inputEmail).should('have.value', testIds.user_validEmail_producer_flow)
      cy.getByData(testIds.auth_inputPassword).type(testIds.user_validPassword_consumer_flow)
      cy.getByData(testIds.auth_inputPassword).should('have.value', testIds.user_validPassword_consumer_flow)
      cy.getByData(testIds.auth_loginButton).click()
      cy.url().should('include', testIds.url_home)
      cy.intercept('GET', '**/trade-pref', {
        fixture: 'OpenSpark/myTrade/trade-pref.json'
      }).as('trade-pref')
      cy.wait('@trade-pref')
      cy.getByData('buy-preference').click()
      cy.url().should('include', 'sellingPreference')
    })

    it('should display all the fields and button', () => {
      cy.getByData(testIds.preference_type).should('be.visible')
      cy.getByData(testIds.questionOutlineIcon).should('be.visible')
      cy.getByData(testIds.FaPlus).should('be.visible')
      cy.getByData(testIds.FaMinus).should('be.visible')
      cy.getByData(testIds.preference_type_input_buy).should('be.visible')
      cy.getByData(testIds.preference_type_unit).should('be.visible')
      cy.getByData(testIds.select_preference_type).should('be.visible')
      cy.getByData(testIds.set_price_per_unit).should('be.visible')
      cy.getByData(testIds.set_price_per_unit_input).should('be.visible')
      cy.getByData(testIds.FaPlus_unit).should('be.visible')
      cy.getByData(testIds.FaMinus_unit).should('be.visible')
      cy.getByData(testIds.select_preference_type_checkbox).should('be.visible')
      cy.getByData(testIds.submit_preference_sell_buy_btn).should('be.visible')
    })
    it('should Buy Energy Units, adjust values with plus/minus buttons, and submit', () => {
      cy.getByData(testIds.preference_type_input_buy).type('100').should('have.value', '100')
      cy.getByData(testIds.FaPlus).click()
      cy.getByData(testIds.preference_type_input_buy).should('have.value', '101')
      cy.getByData(testIds.FaMinus).click()
      cy.getByData(testIds.preference_type_input_buy).should('have.value', '100')
      cy.getByData(testIds.set_price_per_unit_input).type('10').should('have.value', '10')
      cy.getByData(testIds.FaPlus_unit).click()
      cy.getByData(testIds.set_price_per_unit_input).should('have.value', '11')
      cy.getByData(testIds.FaMinus_unit).click()
      cy.getByData(testIds.set_price_per_unit_input).should('have.value', '10')
      cy.getByData(testIds.select_preference_type_checkbox).eq(0).click()
      cy.getByData(testIds.select_preference_type_checkbox).find('input[type="checkbox"]').should('be.checked')
      cy.getByData(testIds.submit_preference_sell_buy_btn).click()
      cy.getByData(testIds.feedback).should('contain.text', 'Success')
    })
  })
})
describe('Check Buying Preference for consumer flow with valid Trade', () => {
  context('Buying Preference for consumer flow', () => {
    before(() => {
      cy.clearAllLocalStorage()
      cy.clearAllCookies()
      cy.visit(testIds.url_base)
      cy.getByData('producer_button').click()
      cy.getByData(testIds.auth_inputEmail).type(testIds.user_validEmail_producer_flow)
      cy.getByData(testIds.auth_inputEmail).should('have.value', testIds.user_validEmail_producer_flow)
      cy.getByData(testIds.auth_inputPassword).type(testIds.user_validPassword_consumer_flow)
      cy.getByData(testIds.auth_inputPassword).should('have.value', testIds.user_validPassword_consumer_flow)
      cy.getByData(testIds.auth_loginButton).click()
      cy.url().should('include', testIds.url_home)
      cy.intercept('GET', '**/trade-pref', {
        fixture: 'OpenSpark/myTrade/trade-pref.json'
      }).as('trade-pref')
      cy.wait('@trade-pref')
      cy.getByData('buy-preference').click()
      cy.url().should('include', 'sellingPreference')
    })

    it('should display all the fields and button', () => {
      cy.getByData(testIds.preference_type).should('be.visible')
      cy.getByData(testIds.questionOutlineIcon).should('be.visible')
      cy.getByData(testIds.FaPlus).should('be.visible')
      cy.getByData(testIds.FaMinus).should('be.visible')
      cy.getByData(testIds.preference_type_input_buy).should('be.visible')
      cy.getByData(testIds.preference_type_unit).should('be.visible')
      cy.getByData(testIds.select_preference_type).should('be.visible')
      cy.getByData(testIds.set_price_per_unit).should('be.visible')
      cy.getByData(testIds.set_price_per_unit_input).should('be.visible')
      cy.getByData(testIds.FaPlus_unit).should('be.visible')
      cy.getByData(testIds.FaMinus_unit).should('be.visible')
      cy.getByData(testIds.select_preference_type_checkbox).should('be.visible')
      cy.getByData(testIds.submit_preference_sell_buy_btn).should('be.visible')
    })
    it('should Buy Energy Units, adjust values with plus/minus buttons, and submit', () => {
      cy.getByData(testIds.preference_type_input_buy).type('100').should('have.value', '100')
      cy.getByData(testIds.FaPlus).click()
      cy.getByData(testIds.preference_type_input_buy).should('have.value', '101')
      cy.getByData(testIds.FaMinus).click()
      cy.getByData(testIds.preference_type_input_buy).should('have.value', '100')
      cy.getByData(testIds.set_price_per_unit_input).type('10').should('have.value', '10')
      cy.getByData(testIds.FaPlus_unit).click()
      cy.getByData(testIds.set_price_per_unit_input).should('have.value', '11')
      cy.getByData(testIds.FaMinus_unit).click()
      cy.getByData(testIds.set_price_per_unit_input).should('have.value', '10')
      cy.getByData(testIds.select_preference_type_checkbox).eq(0).click()
      cy.getByData(testIds.select_preference_type_checkbox).find('input[type="checkbox"]').should('be.checked')
      cy.getByData(testIds.submit_preference_sell_buy_btn).click()
      cy.getByData(testIds.feedback).should('contain.text', 'Success')
    })
  })
})
