import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css'
import '../../styles/globals.scss'
import ToastProvider from '@/components/toast-provider/toast-provider'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode
  params: { locale: string }
}>) {
  return (
    <html lang={locale}>
      <body>
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  )
}
