export const MOCK_MENU_ITEMS = [
  {
    id: 1,
    name: 'Margherita Pizza',
    category: 'Pizza',
    description: 'Classic cheese pizza with fresh mozzarella and basil',
    image: 'https://images.unsplash.com/photo-1601924582975-7e670ea2b1c9?auto=format&fit=crop&w=800&q=80',
    price: 249,
    rating: 4.5,
    isVeg: true,
    preparationTime: '20 mins',
    restaurant: 'Pizza Hub'
  },
  {
    id: 2,
    name: 'Farmhouse Pizza',
    category: 'Pizza',
    description: 'Loaded with fresh veggies and mozzarella cheese',
    image: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?auto=format&fit=crop&w=800&q=80',
    price: 329,
    rating: 4.4,
    isVeg: true,
    preparationTime: '25 mins',
    restaurant: 'Pizza Hub'
  },
  {
    id: 3,
    name: 'Chicken Pepperoni Pizza',
    category: 'Pizza',
    description: 'Pepperoni slices with cheesy goodness',
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=800&q=80',
    price: 399,
    rating: 4.6,
    isVeg: false,
    preparationTime: '25 mins',
    restaurant: 'Pizza Hub'
  },
  {
    id: 4,
    name: 'Veg Burger',
    category: 'Burger',
    description: 'Crispy veg patty with lettuce and mayo',
    image: 'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?auto=format&fit=crop&w=800&q=80',
    price: 149,
    rating: 4.2,
    isVeg: true,
    preparationTime: '15 mins',
    restaurant: 'Burger Point'
  },
  {
    id: 5,
    name: 'Chicken Burger',
    category: 'Burger',
    description: 'Juicy chicken patty with special sauce',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80',
    price: 199,
    rating: 4.5,
    isVeg: false,
    preparationTime: '15 mins',
    restaurant: 'Burger Point'
  },
  {
    id: 6,
    name: 'French Fries',
    category: 'Snacks',
    description: 'Crispy golden fries with seasoning',
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=800&q=80',
    price: 99,
    rating: 4.3,
    isVeg: true,
    preparationTime: '10 mins',
    restaurant: 'Snack Zone'
  },
  {
    id: 7,
    name: 'Paneer Butter Masala',
    category: 'Indian',
    description: 'Rich creamy tomato gravy with paneer',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80',
    price: 259,
    rating: 4.6,
    isVeg: true,
    preparationTime: '25 mins',
    restaurant: 'Spice Villa'
  },
  {
    id: 8,
    name: 'Butter Chicken',
    category: 'Indian',
    description: 'Creamy butter chicken with spices',
    image: 'https://images.unsplash.com/photo-1604908177522-3b8c61e1a7c9?auto=format&fit=crop&w=800&q=80',
    price: 329,
    rating: 4.7,
    isVeg: false,
    preparationTime: '30 mins',
    restaurant: 'Spice Villa'
  },
  {
    id: 9,
    name: 'Veg Biryani',
    category: 'Biryani',
    description: 'Aromatic rice with vegetables and spices',
    image: 'https://images.unsplash.com/photo-1625944525533-473f1a3d7f1a?auto=format&fit=crop&w=800&q=80',
    price: 219,
    rating: 4.3,
    isVeg: true,
    preparationTime: '30 mins',
    restaurant: 'Biryani House'
  },
  {
    id: 10,
    name: 'Chicken Biryani',
    category: 'Biryani',
    description: 'Hyderabadi style chicken biryani',
    image: 'https://images.unsplash.com/photo-1631515243349-e0cb75fb8d37?auto=format&fit=crop&w=800&q=80',
    price: 299,
    rating: 4.8,
    isVeg: false,
    preparationTime: '35 mins',
    restaurant: 'Biryani House'
  },

  {
    id: 11,
    name: 'Masala Dosa',
    category: 'South Indian',
    description: 'Crispy dosa with potato filling',
    image: 'https://images.unsplash.com/photo-1668236543090-82b91b6dfb4e?auto=format&fit=crop&w=800&q=80',
    price: 129,
    rating: 4.4,
    isVeg: true,
    preparationTime: '15 mins',
    restaurant: 'South Treat'
  },
  {
    id: 12,
    name: 'Idli Sambar',
    category: 'South Indian',
    description: 'Soft idlis served with sambar',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&w=800&q=80',
    price: 99,
    rating: 4.2,
    isVeg: true,
    preparationTime: '10 mins',
    restaurant: 'South Treat'
  },
  {
    id: 13,
    name: 'Hakka Noodles',
    category: 'Chinese',
    description: 'Stir-fried noodles with veggies',
    image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80',
    price: 179,
    rating: 4.3,
    isVeg: true,
    preparationTime: '20 mins',
    restaurant: 'China Town'
  },
  {
    id: 14,
    name: 'Chicken Fried Rice',
    category: 'Chinese',
    description: 'Rice tossed with chicken and sauces',
    image: 'https://images.unsplash.com/photo-1604908812120-3fdf1c8d9f1b?auto=format&fit=crop&w=800&q=80',
    price: 209,
    rating: 4.5,
    isVeg: false,
    preparationTime: '20 mins',
    restaurant: 'China Town'
  },
  {
    id: 15,
    name: 'Veg Momos',
    category: 'Snacks',
    description: 'Steamed momos with spicy chutney',
    image: 'https://images.unsplash.com/photo-1628294895950-9805252327bc?auto=format&fit=crop&w=800&q=80',
    price: 149,
    rating: 4.4,
    isVeg: true,
    preparationTime: '15 mins',
    restaurant: 'Momo Junction'
  },

  {
    id: 16,
    name: 'Chicken Momos',
    category: 'Snacks',
    description: 'Juicy chicken-filled momos',
    image: 'https://images.unsplash.com/photo-1627662168223-7b4e9b8d7f62?auto=format&fit=crop&w=800&q=80',
    price: 179,
    rating: 4.6,
    isVeg: false,
    preparationTime: '15 mins',
    restaurant: 'Momo Junction'
  },
  {
    id: 17,
    name: 'Chocolate Cake',
    category: 'Dessert',
    description: 'Rich and moist chocolate cake',
    image: 'https://images.unsplash.com/photo-1601972599720-b9f2d30841ab?auto=format&fit=crop&w=800&q=80',
    price: 199,
    rating: 4.7,
    isVeg: true,
    preparationTime: '10 mins',
    restaurant: 'Sweet Tooth'
  },
  {
    id: 18,
    name: 'Gulab Jamun',
    category: 'Dessert',
    description: 'Soft milk-solid dumplings in syrup',
    image: 'https://images.unsplash.com/photo-1612197528562-1e1a5bb8e4d5?auto=format&fit=crop&w=800&q=80',
    price: 99,
    rating: 4.6,
    isVeg: true,
    preparationTime: '5 mins',
    restaurant: 'Sweet Tooth'
  },
  {
    id: 19,
    name: 'Ice Cream Sundae',
    category: 'Dessert',
    description: 'Vanilla ice cream with chocolate sauce',
    image: 'https://images.unsplash.com/photo-1505253216365-6c57e3bfa1b5?auto=format&fit=crop&w=800&q=80',
    price: 149,
    rating: 4.5,
    isVeg: true,
    preparationTime: '5 mins',
    restaurant: 'Sweet Tooth'
  },
  {
    id: 20,
    name: 'Cold Coffee',
    category: 'Beverages',
    description: 'Chilled coffee with milk',
    image: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=800&q=80',
    price: 129,
    rating: 4.4,
    isVeg: true,
    preparationTime: '5 mins',
    restaurant: 'Cafe Brew'
  },

  {
    id: 21,
    name: 'Cappuccino',
    category: 'Beverages',
    description: 'Hot cappuccino with frothy milk',
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80',
    price: 149,
    rating: 4.3,
    isVeg: true,
    preparationTime: '5 mins',
    restaurant: 'Cafe Brew'
  },
  {
    id: 22,
    name: 'Cheese Sandwich',
    category: 'Sandwich',
    description: 'Grilled sandwich with melted cheese',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80',
    price: 139,
    rating: 4.2,
    isVeg: true,
    preparationTime: '10 mins',
    restaurant: 'Snack Zone'
  },
  {
    id: 23,
    name: 'Club Sandwich',
    category: 'Sandwich',
    description: 'Loaded sandwich with veggies and sauce',
    image: 'https://images.unsplash.com/photo-1553909489-cd47e0907980?auto=format&fit=crop&w=800&q=80',
    price: 179,
    rating: 4.4,
    isVeg: true,
    preparationTime: '12 mins',
    restaurant: 'Snack Zone'
  },
  {
    id: 24,
    name: 'Chicken Wrap',
    category: 'Wraps',
    description: 'Spicy chicken wrap with veggies',
    image: 'https://images.unsplash.com/photo-1625944230945-1b7ddc3c9c6f?auto=format&fit=crop&w=800&q=80',
    price: 199,
    rating: 4.5,
    isVeg: false,
    preparationTime: '15 mins',
    restaurant: 'Wrap It'
  },
  {
    id: 25,
    name: 'Paneer Wrap',
    category: 'Wraps',
    description: 'Paneer wrap with mint chutney',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
    price: 179,
    rating: 4.3,
    isVeg: true,
    preparationTime: '15 mins',
    restaurant: 'Wrap It'
  },

  {
    id: 26,
    name: 'Veg Thali',
    category: 'Indian',
    description: 'Complete Indian veg meal',
    image: 'https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?auto=format&fit=crop&w=800&q=80',
    price: 249,
    rating: 4.6,
    isVeg: true,
    preparationTime: '30 mins',
    restaurant: 'Home Taste'
  },
  {
    id: 27,
    name: 'Chicken Thali',
    category: 'Indian',
    description: 'Traditional chicken thali',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=800&q=80',
    price: 329,
    rating: 4.7,
    isVeg: false,
    preparationTime: '35 mins',
    restaurant: 'Home Taste'
  },
  {
    id: 28,
    name: 'Pav Bhaji',
    category: 'Street Food',
    description: 'Spicy mashed veggies with butter pav',
    image: 'https://images.unsplash.com/photo-1601050690142-4f8c4f5e9a9a?auto=format&fit=crop&w=800&q=80',
    price: 159,
    rating: 4.6,
    isVeg: true,
    preparationTime: '20 mins',
    restaurant: 'Mumbai Tadka'
  },
  {
    id: 29,
    name: 'Vada Pav',
    category: 'Street Food',
    description: 'Mumbai style vada pav',
    image: 'https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?auto=format&fit=crop&w=800&q=80',
    price: 49,
    rating: 4.5,
    isVeg: true,
    preparationTime: '5 mins',
    restaurant: 'Mumbai Tadka'
  },
  {
    id: 30,
    name: 'Samosa',
    category: 'Street Food',
    description: 'Crispy fried samosa',
    image: 'https://images.unsplash.com/photo-1601050690142-4f8c4f5e9a9a?auto=format&fit=crop&w=800&q=80',
    price: 39,
    rating: 4.4,
    isVeg: true,
    preparationTime: '5 mins',
    restaurant: 'Mumbai Tadka'
  },

  {
    id: 31,
    name: 'Tandoori Chicken',
    category: 'Indian',
    description: 'Smoky tandoori chicken',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=800&q=80',
    price: 349,
    rating: 4.7,
    isVeg: false,
    preparationTime: '35 mins',
    restaurant: 'Punjabi Dhaba'
  },
  {
    id: 32,
    name: 'Dal Tadka',
    category: 'Indian',
    description: 'Yellow dal tempered with spices',
    image: 'https://images.unsplash.com/photo-1625944525533-473f1a3d7f1a?auto=format&fit=crop&w=800&q=80',
    price: 189,
    rating: 4.3,
    isVeg: true,
    preparationTime: '20 mins',
    restaurant: 'Punjabi Dhaba'
  },
  {
    id: 33,
    name: 'Jeera Rice',
    category: 'Indian',
    description: 'Basmati rice with cumin',
    image: 'https://images.unsplash.com/photo-1596560548464-f010549b84d7?auto=format&fit=crop&w=800&q=80',
    price: 149,
    rating: 4.2,
    isVeg: true,
    preparationTime: '15 mins',
    restaurant: 'Punjabi Dhaba'
  },
  {
    id: 34,
    name: 'Chicken Shawarma',
    category: 'Middle Eastern',
    description: 'Juicy chicken shawarma roll',
    image: 'https://images.unsplash.com/photo-1617196034738-26c6c6c4d6d7?auto=format&fit=crop&w=800&q=80',
    price: 199,
    rating: 4.6,
    isVeg: false,
    preparationTime: '15 mins',
    restaurant: 'Arabian Grill'
  },
  {
    id: 35,
    name: 'Falafel Wrap',
    category: 'Middle Eastern',
    description: 'Crispy falafel with tahini sauce',
    image: 'https://images.unsplash.com/photo-1593001872095-7d5b3868dd3c?auto=format&fit=crop&w=800&q=80',
    price: 179,
    rating: 4.4,
    isVeg: true,
    preparationTime: '15 mins',
    restaurant: 'Arabian Grill'
  },

  {
    id: 36,
    name: 'Pasta Alfredo',
    category: 'Italian',
    description: 'Creamy white sauce pasta',
    image: 'https://images.unsplash.com/photo-1521389508051-d7ffb5dc8d7c?auto=format&fit=crop&w=800&q=80',
    price: 249,
    rating: 4.5,
    isVeg: true,
    preparationTime: '20 mins',
    restaurant: 'Italiano'
  },
  {
    id: 37,
    name: 'Chicken Pasta',
    category: 'Italian',
    description: 'Pasta tossed with chicken and sauce',
    image: 'https://images.unsplash.com/photo-1598866594230-a7c12756260f?auto=format&fit=crop&w=800&q=80',
    price: 299,
    rating: 4.6,
    isVeg: false,
    preparationTime: '25 mins',
    restaurant: 'Italiano'
  },
  {
    id: 38,
    name: 'Veg Salad',
    category: 'Healthy',
    description: 'Fresh vegetable salad',
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=800&q=80',
    price: 149,
    rating: 4.2,
    isVeg: true,
    preparationTime: '10 mins',
    restaurant: 'Green Bowl'
  },
  {
    id: 39,
    name: 'Grilled Chicken Salad',
    category: 'Healthy',
    description: 'Protein-rich grilled chicken salad',
    image: 'https://images.unsplash.com/photo-1546069901-eacef0df6022?auto=format&fit=crop&w=800&q=80',
    price: 229,
    rating: 4.5,
    isVeg: false,
    preparationTime: '15 mins',
    restaurant: 'Green Bowl'
  },
  {
    id: 40,
    name: 'Fruit Bowl',
    category: 'Healthy',
    description: 'Seasonal fresh fruits',
    image: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?auto=format&fit=crop&w=800&q=80',
    price: 159,
    rating: 4.3,
    isVeg: true,
    preparationTime: '5 mins',
    restaurant: 'Green Bowl'
  },

  {
    id: 41,
    name: 'Milkshake',
    category: 'Beverages',
    description: 'Thick chocolate milkshake',
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=800&q=80',
    price: 179,
    rating: 4.4,
    isVeg: true,
    preparationTime: '5 mins',
    restaurant: 'Cafe Brew'
  },
  {
    id: 42,
    name: 'Lassi',
    category: 'Beverages',
    description: 'Sweet Punjabi lassi',
    image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=800&q=80',
    price: 99,
    rating: 4.5,
    isVeg: true,
    preparationTime: '5 mins',
    restaurant: 'Punjabi Dhaba'
  },
  {
    id: 43,
    name: 'Veg Cutlet',
    category: 'Snacks',
    description: 'Crispy vegetable cutlet',
    image: 'https://images.unsplash.com/photo-1600628422019-4d4d6d1b7e7b?auto=format&fit=crop&w=800&q=80',
    price: 79,
    rating: 4.2,
    isVeg: true,
    preparationTime: '10 mins',
    restaurant: 'Snack Zone'
  },
  {
    id: 44,
    name: 'Chicken Nuggets',
    category: 'Snacks',
    description: 'Crispy chicken nuggets',
    image: 'https://images.unsplash.com/photo-1562967916-eb82221dfb36?auto=format&fit=crop&w=800&q=80',
    price: 199,
    rating: 4.4,
    isVeg: false,
    preparationTime: '10 mins',
    restaurant: 'Snack Zone'
  },
  {
    id: 45,
    name: 'Rasgulla',
    category: 'Dessert',
    description: 'Soft spongy rasgullas',
    image: 'https://images.unsplash.com/photo-1612197528562-1e1a5bb8e4d5?auto=format&fit=crop&w=800&q=80',
    price: 89,
    rating: 4.6,
    isVeg: true,
    preparationTime: '5 mins',
    restaurant: 'Sweet Tooth'
  },
  {
    id: 46,
    name: 'Brownie',
    category: 'Dessert',
    description: 'Chocolate brownie with nuts',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80',
    price: 149,
    rating: 4.7,
    isVeg: true,
    preparationTime: '5 mins',
    restaurant: 'Sweet Tooth'
  },
  {
    id: 47,
    name: 'Veg Soup',
    category: 'Soups',
    description: 'Hot vegetable soup',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80',
    price: 119,
    rating: 4.2,
    isVeg: true,
    preparationTime: '10 mins',
    restaurant: 'China Town'
  },
  {
    id: 48,
    name: 'Chicken Soup',
    category: 'Soups',
    description: 'Warm chicken soup',
    image: 'https://images.unsplash.com/photo-1604908554027-69f3e37f44c6?auto=format&fit=crop&w=800&q=80',
    price: 149,
    rating: 4.4,
    isVeg: false,
    preparationTime: '10 mins',
    restaurant: 'China Town'
  },
  {
    id: 49,
    name: 'Garlic Bread',
    category: 'Snacks',
    description: 'Toasted garlic bread',
    image: 'https://images.unsplash.com/photo-1617191519000-df6b6c8e4c8f?auto=format&fit=crop&w=800&q=80',
    price: 129,
    rating: 4.3,
    isVeg: true,
    preparationTime: '10 mins',
    restaurant: 'Italiano'
  },
  {
    id: 50,
    name: 'Cheese Corn Pizza',
    category: 'Pizza',
    description: 'Sweet corn with melted cheese',
    image: 'https://images.unsplash.com/photo-1548365328-9f547fb0954f?auto=format&fit=crop&w=800&q=80',
    price: 299,
    rating: 4.4,
    isVeg: true,
    preparationTime: '25 mins',
    restaurant: 'Pizza Hub'
  }
]
