const testIds = {
  // general
  goBack: 'go-back',
  feedback: 'feedback-toast',
  loadingIndicator: 'loading-indicator',
  noDataAvailable: 'no-data-available',
  cartButton: 'cart-button',
  location: 'location',
  searchInput: 'search-input',
  searchButton: 'search-button',
  // items
  item_title: 'item-title',
  item_subTitle: 'item-sub-title',
  item_details: 'item-details',
  item_image: 'item-image',
  item_rating: 'item-rating',
  item_description: 'item-description',
  item_price: 'item-price',
  item_quantity: 'item-quantity',
  // urls
  url_base: 'http://localhost:3002',
  url_signup: 'http://localhost:3002/signUp',
  url_home: 'http://localhost:3002/',
  url_search: 'http://localhost:3002/search',
  url_cart: '/cart',
  url_product: '/product',
  url_checkout: '/checkout',
  url_payment: '/paymentMode',
  url_orderDetails: '/orderDetails',
  url_orderConfirmation: '/orderConfirmation',

  // user credentials
  user_validEmail: 'ankit@gmail.com',
  user_validPassword: 'Enterthevoid@123',
  user_invalidPassword: 'Enterthevoid@1234',
  // auth page
  auth_inputEmail: 'input-email',
  auth_inputPassword: 'input-password',
  auth_loginButton: 'login-button',
  auth_registerButton: 'register-button',
  // home page
  homepage_appTitle: 'app-title',
  homepage_appSubtitle: 'app-subtitle',
  homepage_appDescription: 'app-description',
  homepage_appLogo: 'app-logo',
  homepage_footer: 'footer',
  // imported order
  homepage_importOrderContainer: 'imported-orders',
  homepage_viewDetailsButton: 'view-details-button',
  homepage_shoppingListItem: 'shopping-list-item',
  homepage_viewChatGPTList: 'view-chat-gpt-list',
  // search page
  searchpage_products: 'products',
  searchpage_filterContainer: 'filter-container',
  searchpage_filterButton: 'filter-button',
  searchpage_resetBtn: 'reset-button',
  searchpage_sortByPrice: 'sort-by-price',
  searchpage_filterByRating: 'filter-by-rating',
  searchpage_applyFilter: 'apply-filter',
  searchpage_cancelFilter: 'cancel-filter',
  // product page
  productpage_addTocartButton: 'add-to-cart-button',
  productpage_incrementCounter: 'increment-counter',
  productpage_counterValue: 'counter-value',
  productpage_decrementCounter: 'decrement-counter',
  // cart page
  cartpage_emptyImage: 'empty-card-image',
  cartpage_emptyheading: 'empty-card-heading',
  cartpage_emptySubHeading: 'empty-card-subheading',
  cartpage_emptyButton: 'empty-card-button',
  cartpage_productAddToCart: 'productAddtoCart',
  cartpage_itemImage: 'cart-card-image',
  cartpage_itemName: 'cart-item-name',
  cartpage_productPrice: 'product-price',
  cartpage_orderSummaryText: 'order-summary',
  cartpage_totalQuantityText: 'total-qunatity-text',
  cartpage_totalAmountText: 'total-amount-text',
  cartpage_cartOrderButton: 'cart-order-button',
  cartpage_decrementButton: 'decrement-button',
  cartpage_incrementButton: 'increment-button',
  cartpage_trashButton: 'trash-button',
  cartpage_input: 'cart-input',
  // checkout page
  checkoutpage_itemDetails: 'item-details',
  checkoutpage_form: 'form',
  checkoutpage_openForm: 'open-form',
  checkoutpage_name: 'name',
  checkoutpage_mobileNumber: 'mobileNumber',
  checkoutpage_email: 'email',
  checkoutpage_address: 'address',
  checkoutpage_pinCode: 'pinCode',
  checkoutpage_shippingDetails: 'shippingDetails',
  checkoutpage_billingDetails: 'billingDetails',
  checkoutpage_paymentDetails: 'paymentDetails',
  checkoutpage_checkbox: 'checkbox',
  checkoutpage_changeFormDetails: 'changeFormDetails',
  checkoutpage_basePrice: 'base-price',
  checkoutpage_taxes: 'taxes',
  checkoutpage_totalPayment: 'totalPayment',
  checkoutpage_proceedToCheckout: 'proceed-to-checkout',
  //payment page
  paymentpage_radioButton: 'radio-button',
  paymentpage_confirmButton: 'confirm-button',
  paymentpage_creditcardAndDebitCard: 'Credit & Debit Cards',
  paymentpage_addText: 'add',
  paymentpage_image: 'mode-of-payemnt-image',
  paymentpage_visa: 'visa',
  paymentpage_masterCard: 'masterCard',
  paymentpage_phonePay: 'phonePay',
  paymentpage_CashOnDelivery: 'CashOnDelivery',
  //orderConfirmation page
  confirmPageImage: 'confrimPage-image',
  orderConfirmation_successOrderMessage: 'suceess-OrderMessage',
  orderConfirmation_gratefulMessage: 'grateful-message',
  orderConfirmation_orderIdMessage: 'order-message',
  orderConfirmation_trackOrderMessage: 'track-order',
  orderConfirmation_viewOrderButton: 'viewOrderDetails-button',
  orderConfirmation_goBackToHome: 'goBackToHome-button'
}

export { testIds }
