name: Aws-Amplify-Build

on:
  push:
    branches:
      - develop-1.1.0
    paths:
      - 'apps/taxi-bpp-v2/**'
      - 'apps/retail/**'
      - 'apps/mobility-bap/**'
      - 'apps/policy-admin/**'
      - 'apps/tourismV1.1/**'
      - 'apps/dsep/**'
      - 'apps/industry_4.0/**'
      - 'apps/odr-v2/**'
      - 'apps/dsnp-v2/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with: 
          fetch-depth: 2
      
#  taxi-bpp  https://driverapp-dev.becknprotocol.io

      - name: Check for taxi-bpp-v2 changes
        id: check_taxi_bpp_changes
        run: |
          if git diff  HEAD -- apps/taxi-bpp-v2/; then
            echo "No changes in taxi-bpp-v2. Skipping webhook trigger."
            echo "taxi_bpp_changed=false" >> $GITHUB_ENV
          else
            echo "Changes in taxi-bpp-v2 detected."
            curl -X POST -d '{}' "https://webhooks.amplify.ap-south-1.amazonaws.com/prod/webhooks?id=ec00fdf7-9c72-4da0-8ee1-59aeabbe1b4f&token=HKS7KIARWzLIQSGGboGwJoLq34JQjBGPHtkJlCX1na4&operation=startbuild" -H "Content-Type: application/json"
          fi
