name: Build taxi-bpp-v2

on:
  push:
    branches:
      - develop-1.1.0
    paths:
      - 'apps/taxi-bpp-v2/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Check for taxi-bpp-v2 changes
        id: check_taxi_bpp_changes
        run: |
          git fetch
          if git diff --quiet HEAD^ HEAD -- apps/taxi-bpp-v2/; then
            echo "No changes in taxi-bpp-v2. Skipping webhook trigger."
            echo "taxi_bpp_changed=false" >> $GITHUB_ENV
          else
            echo "Changes in taxi-bpp-v2 detected."
            echo "taxi_bpp_changed=true" >> $GITHUB_ENV

      - name: Trigger webhook
        if: env.taxi_bpp_changed == 'true'
        run: |
          curl -X POST -d '{}' "https://webhooks.amplify.ap-south-1.amazonaws.com/prod/webhooks?id=ec00fdf7-9c72-4da0-8ee1-59aeabbe1b4f&token=HKS7KIARWzLIQSGGboGwJoLq34JQjBGPHtkJlCX1na4&operation=startbuild" -H "Content-Type: application/json"
