name: Aws-Amplify-Build

on:
  push:
    branches:
      - develop-1.1.0
    paths:
      - 'apps/taxi-bpp-v2/**'
      - 'apps/retail/**'
      - 'apps/mobility-bap/**'
      - 'apps/policy-admin/**'
      - 'apps/tourismV1.1/**'
      - 'apps/dsep/**'
      - 'apps/industry_4.0/**'
      - 'apps/odr-v2/**'
      - 'apps/dsnp-v2/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Fetch all changes
        run: git fetch --all

#  taxi-bpp  https://driverapp-dev.becknprotocol.io

      - name: Check for taxi-bpp-v2 changes
        id: check_taxi_bpp_changes
        run: |
          if git diff --quiet HEAD^ HEAD -- apps/taxi-bpp-v2/; then
            echo "No changes in taxi-bpp-v2. Skipping webhook trigger."
            echo "taxi_bpp_changed=false" >> $GITHUB_ENV
          else
            echo "Changes in taxi-bpp-v2 detected."
            curl -X POST -d '{}' "https://webhooks.amplify.ap-south-1.amazonaws.com/prod/webhooks?id=ec00fdf7-9c72-4da0-8ee1-59aeabbe1b4f&token=HKS7KIARWzLIQSGGboGwJoLq34JQjBGPHtkJlCX1na4&operation=startbuild" -H "Content-Type: application/json"
          fi

# retail https://retail-dev.becknprotocol.io/
      - name: Check for retail changes
        id: check_retail_app_changes
        run: |
          if git diff --quiet HEAD^ HEAD -- apps/retail/; then
            echo "No changes in retail. Skipping webhook trigger."
            echo "retail_app_changed=false" >> $GITHUB_ENV
          else
            echo "Changes in retail detected."
            curl -X POST -d {} "https://webhooks.amplify.ap-south-1.amazonaws.com/prod/webhooks?id=c7078a5a-3cd0-4ac4-bf24-b732c062f03e&token=uWsFBpwN9xu7y2PA6JhKXby1HHaj3fMgcTyaW4Wo&operation=startbuild" -H "Content-Type:application/json"
          fi

#  mobility-bap https://mobility-dev.becknprotocol.io/
      - name: Check for mobility-bap changes
        id: check_mobility_bap_app_changes
        run: |
          if git diff --quiet HEAD^ HEAD -- apps/mobility-bap/; then
            echo "No changes in mobility-bap. Skipping webhook trigger."
            echo "mobility_bap_app_changed=false" >> $GITHUB_ENV
          else
            echo "Changes in mobility-bap detected."
            curl -X POST -d {} "https://webhooks.amplify.ap-south-1.amazonaws.com/prod/webhooks?id=857795dc-e016-4f24-9337-d1adaa2a4bd6&token=vvr56Nt7mfoPKraNZ6VJCDoxXQtqVCsuPMZzK6m4UI&operation=startbuild" -H "Content-Type:application/json"
          fi


# policy-admin https://policyadmin-dev.becknprotocol.io/
      - name: Check for policy-admin changes
        id: check_policy_admin_changes
        run: |
          if git diff --quiet HEAD^ HEAD -- apps/policy-admin/; then
            echo "No changes in policy-admin. Skipping webhook trigger."
            echo "policy_admin_changed=false" >> $GITHUB_ENV
          else
            echo "Changes in policy-admin detected."
            curl -X POST -d {} "https://webhooks.amplify.ap-south-1.amazonaws.com/prod/webhooks?id=7c612fe0-6304-41ef-aeda-d5fa557a451e&token=w6tddumrZNneSzM1wxzonlYhCRQATyr8TShRIkNVaa8&operation=startbuild" -H "Content-Type:application/json"
          fi

#  tourism-v1.1 https://mobility-cityoflights-dev.becknprotocol.io/
      - name: Check for tourismV1.1 changes
        id: check_tourism_app_changes
        run: |
          if git diff --quiet HEAD^ HEAD -- apps/tourismV1.1/; then
            echo "No changes in tourismV1.1. Skipping webhook trigger."
            echo "tourism_app_changed=false" >> $GITHUB_ENV
          else
            echo "Changes in tourismV1.1 detected."
            curl -X POST -d {} "https://webhooks.amplify.ap-south-1.amazonaws.com/prod/webhooks?id=7f7a514b-4745-4c6c-a694-e137da4cecb8&token=bOrlDggGQ37i19vrVSu763z5pnZQIMBcAQL3dqw59M&operation=startbuild" -H "Content-Type:application/json"
          fi

# OSC https://retail-osc-dev.becknprotocol.io/
      - name: Check for OSC changes
        id: check_osc_app_changes
        run: |
          if git diff --quiet HEAD^ HEAD -- apps/OSC/; then
            echo "No changes in OSC. Skipping webhook trigger."
            echo "osc_app_changed=false" >> $GITHUB_ENV
          else
            echo "Changes in OSC detected."
            curl -X POST -d {} "https://webhooks.amplify.ap-south-1.amazonaws.com/prod/webhooks?id=4deaadd8-321a-46f9-a71e-6916376e8211&token=MJFF6hOOZVcLCI4UfdcBv7jDsmldxgkWLN7VTjP0&operation=startbuild" -H "Content-Type:application/json"
          fi


# dsep https://unified-dsep-dev.becknprotocol.io/
      - name: Check for dsep changes
        id: check_dsep_app_changes
        run: |
          if git diff --quiet HEAD^ HEAD -- apps/dsep/; then
            echo "No changes in dsep. Skipping webhook trigger."
            echo "dsep_app_changed=false" >> $GITHUB_ENV
          else
            echo "Changes in dsep detected."
            curl -X POST -d {} "https://webhooks.amplify.ap-south-1.amazonaws.com/prod/webhooks?id=dd26e0d3-65c0-4e27-a067-9f032110f986&token=FlyIdjzRd0XyE0VBRmCeOmDTntXYmVSKLJxyM3qzNQ&operation=startbuild" -H "Content-Type:application/json"
          fi

# industry_4.0 https://supplyflow-dev.becknprotocol.io/
      - name: Check for industry_4.0 changes
        id: check_industry_4_0_app_changes
        run: |
          if git diff --quiet HEAD^ HEAD -- apps/industry_4.0/; then
            echo "No changes in industry_4.0. Skipping webhook trigger."
            echo "industry_4_0_app_changed=false" >> $GITHUB_ENV
          else
            echo "Changes in industry_4.0 detected."
            curl -X POST -d {} "https://webhooks.amplify.ap-south-1.amazonaws.com/prod/webhooks?id=d77893c3-3f9a-4e59-b680-4397e66cd7c6&token=mxSfAjost006WyC5MsR5Vgm1DRvOVQlvhvODMiiBk&operation=startbuild" -H "Content-Type:application/json"
          fi


# odr https://onlinedisputeresolution-dev.becknprotocol.io/
      - name: Check for odr-v2 changes
        id: check_odr_v2_app_changes
        run: |
          if git diff --quiet HEAD^ HEAD -- apps/odr-v2/; then
            echo "No changes in odr-v2. Skipping webhook trigger."
            echo "odr_v2_app_changed=false" >> $GITHUB_ENV
          else
            echo "Changes in odr-v2 detected."
            curl -X POST -d {} "https://webhooks.amplify.ap-south-1.amazonaws.com/prod/webhooks?id=7d18d2be-8fcd-4cbd-82e3-bfa293eedda1&token=qo8TrlufHhg2SmXeD0sJi38BbopbYlREIPbR6Xf2yI&operation=startbuild" -H "Content-Type:application/json"
          fi


#dsnp-v2 https://socialweb-dev.becknprotocol.io/
      - name: Check for dsnp-v2 changes
        id: check_dsnp_v2_app_changes
        run: |
          if git diff --quiet HEAD^ HEAD -- apps/dsnp-v2/; then
            echo "No changes in dsnp-v2. Skipping webhook trigger."
            echo "dsnp_v2_app_changed=false" >> $GITHUB_ENV
          else
            echo "Changes in dsnp-v2 detected."
            curl -X POST -d {} "https://webhooks.amplify.ap-south-1.amazonaws.com/prod/webhooks?id=cebb1953-5759-4bc5-9261-9a7ecf007afa&token=2xWFyT8e8BXvJOqHZoaFmN5BTGi1AWwyoxDCXWWnc&operation=startbuild" -H "Content-Type:application/json"
          fi

