name: Aws-Amplify-Build

on:
  push:
    branches:
      - develop-1.1.0
    paths:
      - 'apps/taxi-bpp-v2/**'
      - 'apps/retail/**'
      - 'apps/mobility-bap/**'
      - 'apps/policy-admin/**'
      - 'apps/tourismV1.1/**'
      - 'apps/dsep/**'
      - 'apps/industry_4.0/**'
      - 'apps/odr-v2/**'
      - 'apps/dsnp-v2/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      # taxi-bpp-v2
      - name: Check for taxi-bpp-v2 changes
        id: check_taxi_bpp_changes
        run: |
          if git diff --name-only HEAD~1 HEAD | grep '^apps/taxi-bpp-v2/'; then
            echo "Changes in taxi-bpp-v2 detected."
            echo "taxi_bpp_changed=true" >> $GITHUB_ENV
          else
            echo "No changes in taxi-bpp-v2. Skipping webhook trigger."
            echo "taxi_bpp_changed=false" >> $GITHUB_ENV
          fi

      - name: Trigger taxi-bpp-v2 deployment if changes are detected
        if: env.taxi_bpp_changed == 'true'
        run: |
          curl -X POST -d {} "${{ secrets.TAXI_AMPLIFY_WEBHOOK_URL }}" -H "Content-Type:application/json"
